pytest-dev/pytest-xdist

- testing/test_dsession.py
- xdist/dsession.py
- xdist/slavemanage.py
...when the number of nodes is more than half the number of tests. This makes it
possible, for example, to run all tests in parallel, where previous
the maximum parallelization was half of all tests. This fixes #12.
> Do a better job parallelizing the inital batch of tests

- .travis.yml
- testing/test_dsession.py
- tox.ini
- Fix current "python" environment on travis to 3.5
- Updated build matrix to give preference of testing all pytest versions in py27 and py35
- Fix a small regression in `test_report_collection_diff_different`
> Update travis to use more recent python and pytest versions

- OVERVIEW.md
As commented in #18 in [this comment](https://github.com/pytest-dev/pytest-xdist/issues/18#issuecomment-162756387). Comments, oversights and corrections are welcome!
cc @RonnyPfannschmidt @nchammas @hpk42
> First version of architecture overview doc

- testing/acceptance_test.py
- testing/test_plugin.py
Use that instead of an acceptance test: on travis it would result in over 16 slaves being spawned,
which caused weird crashes on multiprocessing module during teardown
:sweat: 
Fix #30
> Unit test "auto" cpu detection

- CHANGELOG
- testing/test_newhooks.py
- xdist/dsession.py
- xdist/newhooks.py
While working on this, I realized the plain `pytest_runtest_logreport` already decorates the `report` object with the `node`, so it seemed unnecessary to implement `pytest_xdist_runtest_logreport`.
Add new `pytest_xdist_node_collection` hook, but thinking about it a little more perhaps `pytest_xdist_collectreport` won't be needed after all.
@thedrow. could you try this branch and see if you can implement what you need in Frozenball/pytest-sugar#65? 
Fix #8
> Add new pytest_xdist_node_collection_finished hook

- .travis.yml
- appveyor.yml
- testing/test_remote.py
- tox.ini
- xdist/__init__.py
Make sure a plain `tox`  command (without parameters) works in all platforms without failures, which facilitates making releases using a "devpi upload/test" workflow. I noticed this problem while working on the `1.14` release and using Travis and AppVeyor to test the generated package.
After this changes, a `devpi test` command works as expected in both platforms. Here's the output for a fictional `1.14.1.dev1` package containing this fixes which I uploaded to my staging area:
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/105911224)
* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-tester/build/1.0.12)
* [Results link on devpi](https://devpi.net/nicoddemus/dev/pytest-xdist/1.14.1.dev1/+toxresults/pytest-xdist-1.14.1.dev1.zip)
Also, make sure we …
> Refactor tox and ci scripts

- .travis.yml
- CHANGELOG
- testing/acceptance_test.py
- testing/test_remote.py
- tox.ini
- xdist/dsession.py
Similar to pytest-dev/pytest#1397
> Skip progress display when in non-terminal 

- xdist/dsession.py
As discussed in #66
I did verify that even after reverting my changes in `remote.py` (b4a7a1a8) this PR fixes the original problem, but I believe we should keep those changes as well because we don't want an internal error exploding if the master node closes unexpectedly.
> Cleanly shutdown workers if session should be interrupted

- README.rst
- testing/test_remote.py
- xdist/remote.py
- xdist/slavemanage.py
While we now have the `worker_id` fixture, having environment variables can help in some situations where you don't have easy access to a fixture, for example in some debugging situations.
> Add env variables to identify workers

- xdist/plugin.py
~~```os.cpu_count()``` is the new way to ask for the number of cpus provided by the system in python 3.
I also added a bit of error handling since ```os.cpu_count()``` may return None if the information is not available and ```multiprocessing.cpu_count()``` may raise ```NotImplementedError```.~~
I found out that multiprocessing.cpu_count() reuses os.cpu_count() so I rebased this PR to just add some error handling for the case where cpu count cannot be determined.
> Handle errors when auto is specified and the number of cpus cannot be detected.

- xdist/plugin.py
Running with py.test 3.0.2 shows:
/usr/lib/python2.7/site-packages/xdist/plugin.py:36: DeprecationWarning: type argument to addoption() is a string 'choice'. For parsearg this is optional and when supplied  should be a type. (options: ('--dist',))
help=("set mode for distributing tests to exec environments.\n\n"
> Don't show warning from pytest 3

- .travis.yml
- CHANGELOG
- appveyor.yml
- setup.py
- testing/acceptance_test.py
- tox.ini
* Support only pytest 2.7 and onward
* Use multiple AppVeyor jobs
Fix #99
> Test with pytest 3.0

- xdist/slavemanage.py
The eventname is being checked to see if it's a substring of "collectionstart", when I think the intent is to check if it's a member of a set that includes the string "collectionstart". This changes the code to be a one-element tuple instead of a string.
> Fix for eventname test

- xdist/plugin.py
1e18f25 corrected an issue with the `type` specification for the `--dist`
argument, setting it to `str`. However, this is the default so there's little
value in specifying it.
> xdist.plugin: Remove unnecessary `type` for --dist

- CHANGELOG
- README.rst
- testing/test_newhooks.py
- xdist/remote.py
I think this change is enough for the purpose of this [issue](https://github.com/pytest-dev/pytest-xdist/issues/118)
Though, I am not really familiar with the project, so please let me know if I am missing something.
> Add worker_id into TestReport

- CHANGELOG
- OVERVIEW.md
According to #89 added notes about new hook and possible scheduler implementations to `CHANGELOG` and `OVERVIEW.md`.
> Added notes about new pytest_xdist_make_scheduler hook

- CHANGELOG
- testing/acceptance_test.py
- xdist/dsession.py
> Mark test as complete at teardown.

- changelog/157.bugfix
- testing/acceptance_test.py
- xdist/dsession.py
This PR reverts the commits introduced by #125 because unfortunately it broke a number of test suites.
I think it is better to release a hot-fix reverting this while we investigate the issue better.
I tested this locally with pytest's own suite.
@RonnyPfannschmidt feel free to merge and make a new release if you agree.
cc @reginaldl 
Fix #157
> Revert PR 125 due to 1.17.0 breakage 

- MANIFEST.in
As discussed in #161, setuptools_scm will automatically
add all version controlled files to the package, so
MANIFEST.in is no longer needed
Fix #161
> Let setuptools_scm manage the files that go into the package

- changelog/168.feature
- testing/test_plugin.py
- xdist/plugin.py
This is more verbose in scripts that run pytest-xdist. It can also help
in some ci-helper scripts like to auto detect if  pytest-xdist should be
installed.
* Name it `$issue_id.$type` for example `588.bug`
```
```
> add '--numprocesses' as long option for '-n'

- changelog/pr_171.bugfix
- testing/test_remote.py
- xdist/remote.py
- xdist/slavemanage.py
This was introduced in PR [164](https://github.com/pytest-dev/pytest-xdist/pull/164). I forgot to serialize/deserialize the sections attribute from ExceptionRepr which is on longrepr. This affects users who append or modify `longrepr.sections` for custom reporting.
Wasn't sure if I should have filed an issue first then a PR. This was a stupid oversight on my part. Sorry for the bug. 
* Name it `$issue_id.$type` for example `588.bug`
```
```
> Serialization/Deserialization was dropping longrepr.sections

- changelog/176.bugfix
- testing/test_remote.py
- xdist/slavemanage.py
This is in reference to issue #176 and a continuation of PR #164 and #171 
I had to instantiate ReprLocals. Added more asserts around comparing the initial report against the result after being serialized, unserialized. 
I think in the initial review @RonnyPfannschmidt mentioned this kind of functionality should me moved in pytest-core. I wholeheartedly agree, since I am terrible at handling it myself. Please be critical of my method since I obviously keep overlooking aspects and introducing new issues. 
* Name it `$issue_id.$type` for example `588.bug`
* Ensure type is one of `removal`, …
> Unserialize reprlocals to a ReprLocal instance

- changelog/105.bugfix
- setup.py
`pytest-xdist` depends on `pytest>=3`.
`pytest 3.0.0` requires `py>=1.4.29`
and latest pytest requires `py>=1.4.33`.
Thus it is unnecessary for pytest-xdist to include
a requirement on `py>=1.4.22`
Fixes https://github.com/pytest-dev/pytest-xdist/issues/105
----
* Name it `$issue_id.$type` for example `588.bug`
```
```
> Removal of unnecessary dependency on py

- changelog/175.bugfix
- testing/test_remote.py
- xdist/slavemanage.py
> Fix internal handling in process_from_remote

- changelog/196.bugfix
- testing/acceptance_test.py
- testing/test_remote.py
- xdist/remote.py
- xdist/slavemanage.py
The problem was because we were not handling `ReprEntryNative` objects, which are generated by ``--tb=native`` command-line flag.
@zzzeek I tested this by cloning the branch `reproduce_pytest_196` from `alembic` repository like you instructed and applying this patch:
```diff
diff --git a/tox.ini b/tox.ini
index c8a3c3e..8e1b1cd 100644
--- a/tox.ini
+++ b/tox.ini
@@ -10,7 +10,7 @@ SQLA_REPO = {env:SQLA_REPO:git+http://git.sqlalchemy.org/sqlalchemy.git}
cov_args=--cov=alembic --cov-report term --cov-report xml
deps=pytest==3.2.0
-     pytest-xdist==1.18.2
+     git+https://github.com/nicoddemus/pytest-xdist.git@traceback-error
mock
sqla079: {[tox]SQLA_REPO}@rel_0_7_9
sqla084: {[tox]SQLA_REPO}@rel_0_8_4
```
Could you please test this in your end as well to double check?
Fix #196
> Fix serialization of native tracebacks

- changelog/92.feature
- setup.cfg
- testing/acceptance_test.py
- xdist/dsession.py
- xdist/remote.py
- xdist/slavemanage.py
> Warnings support

- changelog/214.bugfix
- testing/acceptance_test.py
- xdist/remote.py
> Fix crash when transferring internal pytest warnings from workers to the master node

- changelog/124.bugfix
- changelog/206.feature
- testing/acceptance_test.py
- xdist/dsession.py
- xdist/remote.py
- xdist/slavemanage.py
While trying to fix #124, I realized the root of the problem was that xdist was trying to identify when a test was "done" on a worker by looking at the report from the `pytest_runtest_logreport`, but this is a problem because it is not entirely obvious when a test is actually "done". `pytest_runtest_logreport` is called for all testing stages, `setup`, `call` and `teardown`, and those stages are called or not depending on specific outcomes:
* a failed `setup` prevent's `call` and `teardown` stages;
* a failed `call` will follow with a `teardown` stage;
And plugins might even affect that by implementing `pytest_runtest_protocol` themselves.
So I figured the problem was trying to implicitly figure out if a test was done based on that information.
To solve this I created an explicit event …
> Identify correct test crashed during teardown and support multiple test logs from plugins

- changelog/45.bugfix
- testing/acceptance_test.py
- xdist/dsession.py
If the workers are crashing and the restart limit has been met, we need to stop listening for events and trigger an internal error. This is related to #45 
```
```
> Stop looping if all workers have died

- changelog/5.bugfix
- testing/acceptance_test.py
- testing/test_plugin.py
- xdist/plugin.py
> Don't create DSession in collect-only mode

- xdist/plugin.py
It might not be clear that pytest-xdist is used at all, and this should
help users to make --pdb work.
> Improve UsageError when used with --pdb

- .gitignore
- .travis.yml
- README.rst
- appveyor.yml
- changelog/259.removal
- setup.py
- testing/acceptance_test.py
- testing/conftest.py
- testing/test_dsession.py
- tox.ini
- xdist/remote.py
- xdist/scheduler/loadscope.py
Pytest and Py have both dropped Python 2.6 as it's been EOL for 4 years.
Also remove some redundant Python 3.2 code (also EOL and looks like it's already dropped), some minor code cleanup, and add a Python version badge.
---
```
```
>  Drop support for EOL Python 2.6

- .gitignore
- README.rst
- changelog/242.feature
- testing/acceptance_test.py
- xdist/dsession.py
- xdist/plugin.py
- xdist/scheduler/__init__.py
- xdist/scheduler/filescope.py
- xdist/scheduler/loadscope.py
Hi,
this PR includes a new way of load-distributing tests by the file they reside in.
The implementation is a very simple change of LoadScopeScheduling.
The reason to have this is that in a project I'm working on, there is a single shared ressource per test file, which can't be used concurrently. Unfortunately, just scheduling the tests in one class on the same executor does not help, as there are different test classes, representing different configurations of the shared ressource in each file.
Thus, the proposed LoadFileScheduling.
* Make sure to use full sentences with correct …
> Load-Distribute test cases by filename

- changelog/266.feature
- testing/acceptance_test.py
- xdist/dsession.py
- xdist/remote.py
- xdist/slavemanage.py
Handle the new `pytest_runtest_logfinish` hook introduced in pytest-dev/pytest#3102, which will be released in pytest 3.4.
> Add support for the new pytest_runtest_logfinish hook (pytest 3.4)

- .gitignore
- README.rst
- changelog/234.trivial
- testing/acceptance_test.py
- testing/test_dsession.py
- testing/test_newhooks.py
- testing/test_plugin.py
- testing/test_remote.py
- testing/test_slavemanage.py
- xdist/dsession.py
- xdist/looponfail.py
- xdist/plugin.py
- xdist/remote.py
- xdist/scheduler/each.py
- xdist/scheduler/load.py
- xdist/scheduler/loadscope.py
- xdist/workermanage.py
Use master/worker terminologi in arguments
> #234 use master/worker terminology

- README.rst
I think this improves the README to be more friendly to newcomers:
* `-n` and its new `loadscope` and `loadfile` options are close and more prominent.
* Changed all "sub-sub-titles" to "sub-titles" because they read better 
* Mention `pytest-forked` 
My [fork](https://github.com/nicoddemus/pytest-xdist/tree/titles-readme) can be used for reviewing.
> Improve README to be more newcomer friendly

- changelog/257.bugfix
- testing/acceptance_test.py
- xdist/scheduler/loadscope.py
> Ensure loadscope and loadfile work when the first scope has one work unit

- changelog/285.bugfix
- xdist/workermanage.py
Fix #285
Fix pytest-dev/pytest-cov#191
> Add backward compatibility for ``slaveoutput`` attribute to ``WorkerController`` instances

- changelog/9.bugfix
- testing/test_plugin.py
- xdist/plugin.py
An attempt to fix the #9 issue as it causes trouble in Travis. 
As state by the [doc](https://docs.python.org/3/library/os.html#os.cpu_count), `cpu_count`
doesn't return the number of usable CPUs.
> plugin: get cpu_count from sched_getaffinity

- CHANGELOG.rst
- HOWTORELEASE.rst
- changelog/297.trivial.rst
- changelog/9.bugfix
- dev-requirements.txt
- tox.ini
@RonnyPfannschmidt, on this same PR I have changed the release process to use `tox` like we did with the other projects. The process is well known by now so I think it would be OK to do both on the same PR (although in different commits of course), but let me know if you prefer to do this in two PRs instead.
> Release 1.22.3

- .travis.yml
- appveyor.yml
- changelog/305.bugfix.rst
- setup.py
- testing/test_remote.py
- testing/test_slavemanage.py
- tox.ini
- xdist/dsession.py
- xdist/looponfail.py
- xdist/report.py
- xdist/workermanage.py
Also remove some unnecessary references to py.builtin
Fix #305
> Remove last references to obsolete py.code

- changelog/316.bugfix
- testing/test_plugin.py
- xdist/plugin.py
Closes #316
Not sure if this worth test.
> Workaround cpu detection on Travis CI

- .travis.yml
- CHANGELOG.rst
- appveyor.yml
- changelog/321.bugfix.rst
- setup.py
- tox.ini
This release reverts the change that dropped support for older pytest versions. We should consider this change only for `1.23`.
Issues:
https://github.com/pytest-dev/pytest/issues/3724
https://github.com/pytest-dev/pytest-xdist/issues/319
> Revert dropped support to old pytest versions

- changelog/330.feature.rst
- testing/test_remote.py
- xdist/dsession.py
- xdist/remote.py
Do not send the collection report events when the collection was successful
because master only needs the failed ones.
Fix #330
> Optimize collection performance

- changelog/351.bugfix
- testing/acceptance_test.py
- tox.ini
- xdist/scheduler/each.py
- xdist/scheduler/load.py
- xdist/scheduler/loadscope.py
Remote pytest_runtestloop requires at least 2 tests, or a test
and a shutdown command. In case of inter test locking, for
example using a file lock, the tests could deadlock, since the
shutdown command would not be enqueued, and the last test of a
worker would never finish, and would not allow another worker
to make progress.
```
Fix issue with non-ascii contents in doctest …
```
> Issue node shutdown on empty workload

- changelog/337.feature
- changelog/337.feature.rst
- testing/test_plugin.py
- xdist/plugin.py
- xdist/remote.py
It limits the maximum number of workers when using --numprocesses=auto
> Add --maxprocesses option to use with --numprocesses=auto

- xdist/scheduler/__init__.py
- xdist/scheduler/loadfile.py
This makes it consistent with the option (--dist=loadfile) and the other
scheduling file (loadscope.py)
> Rename filescope to loadfile

- changelog/332.bugfix.rst
- testing/test_remote.py
- xdist/dsession.py
- xdist/remote.py
> Fix handling of skipped modules with pytest.skip at module level

- changelog/378.bugfix.rst
- xdist/workermanage.py
When monkeypatching gevent, pipe errors are output as OSError not IOError.
https://github.com/gevent/gevent/issues/186
> fix a bug with gevent monkeypatch

- changelog/384.bugfix.rst
- changelog/390.bugfix.rst
- xdist/remote.py
Noticed this while working on the removal of the legacy warning system on pytest
> Prepare for the removal of pytest_logwarning in pytest 4.1

- changelog/388.feature.rst
- testing/test_remote.py
- xdist/remote.py
- xdist/workermanage.py
This gets used e.g. by argparse for the "prog" part.
We could explicitly pass it through and/or set it on
config._parser.prog, but that is a bit tedious just for this use case,
and it looks like "simulating" the main prog here appears to not be that
bad of a hack after all.
Fixes https://github.com/pytest-dev/pytest-xdist/issues/358, Fixes #384.
> Pass and use original sys.argv to/with workers

- testing/test_remote.py
Not sure why this started to fail only on `features` (see https://travis-ci.org/pytest-dev/pytest-xdist/builds/467106087?utm_source=github_status&utm_medium=notification), but this seems to fix it in all versions, although I'm not sure it is correct.
> Fix test_remote_usage_prog which started to break with pytest@features

- testing/acceptance_test.py
Follow up to: https://github.com/pytest-dev/pytest-xdist/pull/379#issuecomment-452261290
> Skip config.warn tests in pytest 4.1

- changelog/376.feature.rst
- xdist/remote.py
- xdist/workermanage.py
Based on: https://github.com/pytest-dev/pytest-xdist/pull/396
Fix #376
> Do not change PYTHONPATH or sys.path on workers

- changelog/379.bugfix.rst
- testing/acceptance_test.py
- xdist/remote.py
```
```
I was running into the same issue addressed in #349, except instead of failing to serialize an arg of the warning, I was unable to serialize a warning detail of the warning. To reproduce the error, you can cause a ResourceWarning due to an unclosed socket. One of the warning details will be the socket that wasn't …
> Check that we can serialize the warning detail attr

- CHANGELOG.rst
- changelog/406.bugfix.rst
- xdist/remote.py
> Handle pytest_logwarning deprecation better and prepare next release

- changelog/415.feature
- testing/test_plugin.py
- testing/test_remote.py
- xdist/plugin.py
I was getting annoyed by changing `pytest -ff -n=auto ...` command when I wanted to append only `--pdb`. With this PR one can use `-n=auto` and anytime simply append `--pdb` without getting the `UsageError`.
> Improve behavior of --numprocesses=auto and --pdb

- xdist/workermanage.py
Apparently unused since 2efb059 (2010).
> Remove unuses NodeManager._nodesready

- xdist/looponfail.py
- xdist/plugin.py
This is required with `-p no:debugging`.
Ref: https://github.com/pytest-dev/pytest/pull/4967.
> Use default with usepdb option

- changelog/426.feature.rst
- setup.py
- testing/test_remote.py
- xdist/remote.py
- xdist/workermanage.py
Replaces xdist's own serialization code with pytest's 4.4 serialization hooks.
This also means that the next pytest-xdist release will require `pytest>=4.4`.
> Serialization hooks (requires pytest 4.4)

- .pre-commit-config.yaml
- .travis.yml
- appveyor.yml
- tox.ini
* Use Python 3.7 as preferred Python 3 interpreter
* Do not test pytest `master` and `features` branches on
Python 2.7, as those branches no longer support Python 2.7/3.4
> Improve CI: drop testing pytest master on py27, use py37

- changelog/226.feature.rst
- src/xdist/dsession.py
- testing/test_dsession.py
> Use "nodes * 4" as default for --max-worker-restart

- changelog/435.bugfix.rst
- changelog/435.feature.rst
- src/xdist/dsession.py
- testing/acceptance_test.py
Also show the reason of the session being interrupted
in the warnings summary
Fix #435
> Do not show internal error when running out of workers

- changelog/448.feature.rst
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
**EDIT**
Decided to keep the old way still working for now.
Fix #6
Fix #445
---
**ORIGINAL POST**
While investigating a recent node id bug (#445) I decided to play
with config initialization, around the idea of initializing the config
on the remote *exactly* how we initialize the config object on pytest.main()
One thing that immediately broke all tests was *inprocess* pytester runs,
but other than that just a few tests failed which I find encouraging.
While this patch is in no way even remotely ready, I would like to get
opinions if the overall idea of initializing the config object
like this is sound.
> Use Config.invocation_params for consistent worker initialization

- changelog/467.bugfix.rst
- src/xdist/dsession.py
- src/xdist/plugin.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
This fixes an issue where the pluggy plugin manager returns None if a plugin is not loaded instead of raising an error.
It also makes terminal optional in plugin code.
> Fix issues related to running xdist with the terminal plugin disabled

- README.rst
- testing/acceptance_test.py
> Add an example on how to share session fixture data to README

- .appveyor.yml
- .pre-commit-config.yaml
- .travis.yml
- changelog/475.removal
- setup.py
- src/xdist/dsession.py
- src/xdist/looponfail.py
- src/xdist/scheduler/loadscope.py
- src/xdist/workermanage.py
- testing/test_remote.py
- testing/test_slavemanage.py
- tox.ini
```
```
---
Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
The latest pytest 5.x series no longer supports it. More info: …
> Drop support for EOL Python 3.4

- testing/acceptance_test.py
I suggest we xmark these tests for the time being until pytest upstream issues are resolved.
The failure of `testdir.tmpdir` on Python 2 is
`/tmp/pytest-of-svenstaro/pytest-326/test_basetemp_in_subprocesses0/runpytest-0/popen-gw0/test_send0`
while in Python 3 it is 
`/tmp/pytest-of-svenstaro/pytest-327/tmp-test_basetemp_in_subprocesses0/pytest-of-svenstaro/pytest-0/test_send0`
It's not an optimal fix but at least we'll be able to more easily notice actual test failure in `pytest-xdist`-specific code again. Currently, everything just fails which isn't optimal.
> Ignore Python 3.8 specific failure in pytest for now

- README.rst
- changelog/524.feature
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/test_newhooks.py
- testing/test_plugin.py
- testing/test_remote.py
This fixes my own itch #524. I think this is a very useful and simple global pre-shared state variable for some configurations.
```
```
> Add global testrun uid

- src/xdist/workermanage.py
This replaces `list.append()` with list comprehensions to simplify the workermanagement code. This might also come with some minor performance benefits.
> Prefer list comprehensions over list.append()

- MANIFEST.in
These files don't make sense outside of the git respository.
> Exclude SCM and CI files from distribution

- src/xdist/dsession.py
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/conftest.py
* Fix the autouse fixture which diverts atexit.register calls to support the correct signature.
* Support the new `pytest_warning_recorded` hook.
> Fix compatibility with pytest master

- changelog/558.bugfix.rst
- src/xdist/workermanage.py
- testing/acceptance_test.py
> Fix rsyncdirs usage with pytest 6.0

- changelog/562.bugfix.rst
- src/xdist/remote.py
- testing/acceptance_test.py
> Do not trigger pytest_warning_captured in pytest 6.0+

- README.rst
* Describe ``--numprocesses`` as the long form of ``-n``.
* Describe hidden ``--dist no`` option.
* Remove version annotations (it's been 2.5 years since the most recent mentioned version).
* Consistently use ``--flag value`` rather than ``--flag=value``.
* Drop tease about customization of test grouping.
* General language improvements to better describe how this all works.
> Improve description of testing with multiple CPU's

- testing/acceptance_test.py
- testing/test_looponfail.py
> Increase pexpect timeouts to prevent tests from failing

- changelog/478.bugfix.rst
- testing/acceptance_test.py
Since 953a3f0 options are parsed already, e.g. "-v" from
`$PYTEST_ADDOPTS`, and therefore `$PYTEST_ADDOPTS` should be unset for
child processes.
> tests: check that PYTEST_ADDOPTS is not processed twice

- changelog/549.bugfix
- changelog/549.feature.rst
- src/xdist/plugin.py
- testing/test_plugin.py
> Make "--pdb" imply "--dist no"

- changelog/553.bugfix.rst
- setup.py
- src/xdist/plugin.py
- testing/test_plugin.py
> Use psutil.cpu_count(logical=False) in auto_detect_cpus()

- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
More follow-up for #571, removing conditionals which exist for now-unsupported old versions of pytest.
> Remove compat for pytest < 6

- CHANGELOG.rst
- changelog/471.bugfix
- changelog/504.feature.rst
- changelog/541.removal.rst
- changelog/541.trivial.rst
- changelog/553.bugfix.rst
- changelog/569.removal.rst
The py38-windows build will fail due to https://github.com/pytest-dev/pytest/issues/7638, but it is not related to pytest-xdist and will be fixed in the next pytest release.
> Prepare release 2.0.0

- .appveyor.yml
- .travis.yml
- README.rst
- changelog/585.feature.rst
- changelog/585.trivial.rst
- setup.cfg
- setup.py
- src/xdist/newhooks.py
- src/xdist/plugin.py
- testing/test_plugin.py
- tox.ini
This reverts the behavior we had before psutil was a hard dependency, but opens up the possibility of customization through the `pytest_xdist_auto_num_workers` hook, also making things like #477 possible.
cc @utapyngo
Fix #585
> Make psutil dependency optional and introduce pytest_xdist_auto_num_workers

- changelog/608.feature.rst
- src/xdist/dsession.py
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
This should help users diagnose internal errors in workers like exceptions from hooks or in pytest itself.
> Propagate internal errors to the master node

- changelog/623.bugfix.rst
- src/xdist/remote.py
calculate topdir based on config.rootpath/rootdir
addresses pytest-dev/pytest#8251
```
```
> prepare for Node.fspath deprecation

- README.rst
- changelog/592.trivial.rst
- src/xdist/__init__.py
- src/xdist/dsession.py
- src/xdist/newhooks.py
- src/xdist/plugin.py
- src/xdist/remote.py
- testing/acceptance_test.py
Replace master with controller where ever we can
the helper `is_xdist_master` still needs a deprecation
the return value of the worker id finder needs a breaking change to remove the `master` value
addresses part of #592
> prepare #592: replace master with controller where we can

- changelog/638.bugfix.rst
- tox.ini
It seems that the name of the master branch has been changed to main in the pytest repository.
> [HOTFIX] rename pytest's branch(master to main)

- .pre-commit-config.yaml
- src/xdist/newhooks.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/test_newhooks.py
- testing/test_remote.py
Use `pre-commit autoupdate` to upgrade, and follow the message from `pre-commit-hooks` to move to the official `flake8` hook.
> Upgrade pre-commit hooks

- .github/workflows/main.yml
- README.rst
- changelog/654.removal.rst
- setup.py
- tox.ini
pytest no longer supports it, and our CI is broken because of it.
Also removed `linting` given we are using pre-commit.ci.
Should we run pyupgrade as well?
> Drop Python 3.5 support

- CHANGELOG.rst
- changelog/650.feature.rst
- src/xdist/dsession.py
- src/xdist/newhooks.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadscope.py
- testing/test_newhooks.py
fixes #650, allows a hook to handle a crashitem (if handled, will be put back into test queue).
hook runs in controller, is responsible for communicating status to nodes if needed.
note: I thought of using a file for communication, but ideas welcome. rerunfailures uses `pytest_runtest_protocol`, so I will need to pass a message from this hook (in the controller) to that hook (in the node).
linked pr: pytest-dev/pytest-rerunfailures#158
> add new pytest_handlecrashitem hook

- changelog/646.feature.rst
- src/xdist/plugin.py
- testing/test_plugin.py
With the change to physical CPU count in #560, test sets that are run with `psutil` installed and that are not CPU-bound (in my case, with lots of network activity) take roughly twice as long to execute on hyperthreaded CPUs. Add a new choice `logical` for flag `--numprocesses` for use cases like this.
This implementation is a bit weird because of the multiple fallback paths in `pytest_xdist_auto_num_workers()` which all return the logical CPU count already, but I don't see a better option.
Testing:
- Ran `tox` against all but `python3.5` on Linux:
```
$ python3.9 -m tox -p
...
✔ OK linting in 5.201 seconds
✔ OK py38-psutil in 7.751 seconds
✔ OK py39-pytestlatest in 39.017 seconds
✔ OK py38-pytestlatest in 39.792 seconds
✔ OK py38-pytestmain in 42.884 seconds
✔ OK py36-pytestlatest in …
```
> Add explicit 'logical' choice to --numprocesses flag

- changelog/421.bugfix.rst
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/test_remote.py
> fix sys.path for local workers  Fixes #421

- testing/acceptance_test.py
`--debug` now receives an optional file, so the way the test
was calling pytest made it seem like it was passing the python file
file as the debug file.
> Fix test_fixture_teardown_failure for pytest master

- .github/workflows/main.yml
- README.rst
- changelog/696.feature.rst
- setup.py
- src/xdist/remote.py
- tox.ini
setproctitle() changes the process name, particularly in top/ps output
on posix-y systems.  This is very useful to get some transparency on
what's going on, especially if a test starts taking a very long time or
straight up hangs.
This is strictly a "bonus goodie", if setproctitle is not available,
it's not used, and any errors are ignored silently.
> Use setproctitle if available to show state

- .github/workflows/main.yml
- changelog/704.feature
- setup.py
- tox.ini
```
```
---
Python 3.10.0 final is due for release in October:
* https://www.python.org/dev/peps/pep-0619/
The final release candidate is now out and the Python release team has issued a call to action for community members:
> We strongly encourage maintainers of third-party Python projects to prepare their projects for …
> Add support for Python 3.10

- changelog/708.trivial.rst
- src/xdist/newhooks.py
Noticed while reviewing https://github.com/pytest-dev/pytest/pull/9118.
> Use modern options configurations for hooks

- .pre-commit-config.yaml
- changelog/719.trivial.rst
- changelog/720.trivial.rst
- changelog/721.trivial.rst
- changelog/722.feature.rst
- pyproject.toml
- setup.cfg
- setup.py
- src/xdist/looponfail.py
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/conftest.py
- testing/test_dsession.py
- testing/test_looponfail.py
- testing/test_newhooks.py
- testing/test_plugin.py
- testing/test_remote.py
- testing/test_workermanage.py
- tox.ini
Before we release pytest 7 I figured that pytest-xdist should be ready for it.
Please see the commits for all of the changes. I can break it down to multiple PRs if preferred.
> Modernize packaging, require pytest 6.2, prepare for pytest 7, other changes

- changelog/468.deprecation.rst
- example/boxed.txt
- src/xdist/plugin.py
- testing/acceptance_test.py
This will allow removing the pytest-forked dependency in the future.
Refs #468.
> Deprecate `--boxed`

- testing/acceptance_test.py
This test started to fail in the 'py38-pytestmain' environment, the cause being `PytestRemovedIn7Warning` being raised by the `conftest.py` file of the test itself. Ignoring it is fine, the purpose of the test is to ensure the hook is not called by `pytest-xdist`.
> Fix test_warning_captured_deprecated_in_pytest_6

- README.rst
- changelog/733.feature.rst
- src/xdist/dsession.py
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/scheduler/__init__.py
- src/xdist/scheduler/loadgroup.py
- testing/acceptance_test.py
There are currently several options for distributing tests,
but there is still no suitable option for the following cases:
In this case, it is efficient to divide all tests into different sessions.
```python
@pytest.mark.parametrize('param', [A, B, C, D])
def test_something_heavy(param):
do_something_heavy_test
```
In this case, it is efficient to run all tests in the same session.
```python
def test_something_light_1(heavy_fixture_cannot_filelock):
do_something_light_test
def test_something_light_2(heavy_fixture_cannot_filelock):
do_something_light_test
def test_something_light_3(heavy_fixture_cannot_filelock):
do_something_light_test
```
If you use the loadscope option, all tests in Case 1 are performed in same session,
If the load option is used, all tests of Case 2 may be performed in …
> Create new dist option 'loadgroup'

- .pre-commit-config.yaml
- docs/conf.py
- docs/distribution.rst
- docs/how-to.rst
- testing/test_looponfail.py
This is to add instructions into the documentation to create one file for each worker, as agreed [here](https://github.com/pytest-dev/pytest-xdist/issues/331#issuecomment-1047019487).
> Add instructions to create one file for each worker

- changelog/791.doc
- docs/distribution.rst
Document the pytest_xdist_auto_num_workers hook
I also reorganized the `-n` section slightly, attempting to put the most generally useful information first, and dive into details later.
The feature and tests were added in #590.
> Document the pytest_xdist_auto_num_workers hook

- testing/acceptance_test.py
Reproduces:
INTERNALERROR> TypeError: unhashable type: 'ExceptionChainRepr'
Ref: https://github.com/pytest-dev/pytest-xdist/issues/515
Ref: https://github.com/pytest-dev/pytest/pull/6988
> Add test_collection_crash

- changelog/823.trivial.rst
- src/xdist/workermanage.py
afaict this shouldn't matter since this only supports `pytest` now (and that root is included)
> remove py._pydir as rsync candidate

- changelog/812.feature
- src/xdist/scheduler/load.py
- testing/test_dsession.py
pytest orders tests for optimal sequential execution - i. e. avoiding
unnecessary setup and teardown of fixtures. So executing tests in consecutive
chunks is important for optimal performance.
Commit 09d79ace356ebf14d221cecd3fd8002d075a2034 optimized test distribution for
the corner case, when the number of tests is less than 2 * number of nodes.
At the same time, it made initial test distribution worse for all other cases.
If some tests use some fixture, and these tests fit into the initial batch,
the fixture will be created min(n_tests, n_workers) times, no matter how many
other tests there are. With the old algorithm (before
09d79ace356ebf14d221cecd3fd8002d075a2034), if there are enough tests not using
the fixture, the fixture was created only once.
So restore the old behavior for …
> Restore old initial batch distribution logic in LoadScheduling

- CHANGELOG.rst
- changelog/468.removal.rst
- changelog/468.trivial.rst
- docs/boxed.rst
- docs/index.rst
- setup.cfg
- src/xdist/plugin.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/test_plugin.py
> Remove --boxed and pytest-forked dependency

- pyproject.toml
- src/xdist/looponfail.py
- src/xdist/plugin.py
- testing/acceptance_test.py
> Deprecate looponfail plugin

- changelog/792.feature
- changelog/829.doc
- docs/distribution.rst
- src/xdist/plugin.py
- testing/test_plugin.py
A few additional tests for existing functionality are added too.
And the ``-n logical`` option is documented.
Fixes: https://github.com/pytest-dev/pytest-xdist/issues/792
> Get `-nauto` default from `PYTEST_XDIST_AUTO_NUM_WORKERS`

- docs/index.rst
- docs/remote.rst
- src/xdist/looponfail.py
- src/xdist/newhooks.py
- src/xdist/plugin.py
> Deprecate rsync support

- .github/workflows/main.yml
- changelog/812.feature
- pyproject.toml
- setup.cfg
- setup.py
- src/xdist/plugin.py
- src/xdist/remote.py
- testing/test_plugin.py
* drop empty setup.py which "breaks" on incomplete build envs
* use the build package to build the dist
* update the gh workflow to use it
fixup noise from pre-commit
addresses the artifact building issues seen in #830 
left without changelog data to ensure easy merge into the release branch for @nicoddemus later
> fix and update packaging

- changelog/789.feature.rst
- src/xdist/plugin.py
- testing/acceptance_test.py
> Let users configure dist mode in the configuration file

- changelog/855.feature
- src/xdist/plugin.py
- src/xdist/scheduler/load.py
- testing/test_dsession.py
Maximum number of tests scheduled in one step.
Setting it to 1 will force pytest to send tests to workers one by one - might be useful for a small number of slow tests.
Larger numbers will allow the scheduler to submit consecutive chunks of tests to workers - allows reusing fixtures.
Unlimited if not set.
Fixes #855
Fixes #255
> Add --maxschedchunk CLI option

- changelog/858.feature
- docs/distribution.rst
- src/xdist/dsession.py
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/scheduler/__init__.py
- src/xdist/scheduler/worksteal.py
- src/xdist/workermanage.py
- testing/test_dsession.py
- testing/test_remote.py
> Implement work-stealing scheduler

- testing/test_dsession.py
The expected number of nodes didn't match throughout the test code.
> Fix some LoadScheduling tests

- docs/known-limitations.rst
Some minor typo fixes.
```
```
> doc: fix typos in known limitations

- changelog/863.doc
- docs/known-limitations.rst
> Document limitations for debugging as well as a workaround (#863)

- changelog/870.trivial
- testing/test_plugin.py
> Tests: Unset PYTEST_XDIST_AUTO_NUM_WORKERS when the behavior without the envvar is asserted

- docs/how-to.rst
- Not necessary
- Not necessary, just a docs change
> docs: Remove unused statement in one-log-per-worker example

- changelog/884.bugfix
- src/xdist/remote.py
- testing/test_remote.py
> Fix hang caused by `steal` command with empty test queue

- docs/distribution.rst
- src/xdist/plugin.py
The CLI flag was introduced in https://github.com/pytest-dev/pytest-xdist/pull/857, I took a while to find it because it wasn't in Read The Docs.
I guess this does not need its own changelog entry.
----------------
```
```
> Improve docs of maxschedchunk

- changelog/555.improvement.rst
- src/xdist/dsession.py
- testing/acceptance_test.py
- testing/test_dsession.py
> Make collection progress output less verbose

- .github/workflows/deploy.yml
- RELEASING.rst
Following recent discussions, this changes the development process as follows:
1. The deploy is now manually triggered after the release PR is approved.
2. The deploy workflow tags the repository only after the package has been published to PyPI.
3. Use PyPI trusted publishers instead of API tokens.
---
After this gets merged, I plan to configure the environment in the repository settings, and enable trusted publishing on PyPI (-- or not, @RonnyPfannschmidt might know more about the status of PyPI organizations for deployment).
> Deploy via a protected environment and using PyPI trusted publishers

- .github/workflows/test.yml
- CHANGELOG.rst
- changelog/555.improvement.rst
- setup.cfg
We will also use this opportunity to test the new deploy workflow. 👍 
(Note that now release branches *must* be pushed to the main repository, no longer to the forks).
> Release 3.3.0

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Improvements based on #905:
* Fix tag creation in deploy workflow
* Use same package in all test runs
> CI improvements

- changelog/907.bugfix.rst
- src/xdist/dsession.py
Hopefully this fixes #907, as seems this is the only change in #901 which is somehow related.
> Avoid unnecessary rinfo calls after creating gateways

- docs/remote.rst
Related to #839
cc @benjamin-kirkbride
> Docs: clarify that only rsync support is deprecated

- docs/how-it-works.rst
Fix typo in `how-it-works.rst`: `index` -> `instead`
---
- Not necessary, small typo fix
- Not necessary, small typo fix
> Docs: fix typo `index` -> `instead`

- changelog/963.improvement.rst
- src/xdist/dsession.py
- testing/acceptance_test.py
Currently, a reason to terminate early (e.g. test failure with --exitfail
option set) causes DSession to immediately raise an Interrupt exception.
Subsequent reports generated by the workers, during the shutdown phase, are
discarded.
One consequence is that, for the failing test, teardown and testfinish are
ignored, which prevents corresponding hooks pytest_runtest_logreport and
pytest_runtest_logfinish being executed for the failing test (this problem
covered in #54). The reporting of tests executing in other workers is also left in an
indeterminate state. This can affect other plugin code.
This is a relatively simple fix, which appears to have minimal and, I think,
acceptable impact on text execution behaviour. 
The observable differences are differences in what is reported about a test …
> Properly wait for workers when test run terminates early.

- .github/dependabot.yml
- changelog/1015.vendor
Creates automatic pull requests to upgrade GitHub Actions which will resolve the warnings like at the bottom right of https://github.com/pytest-dev/pytest-xdist/actions/runs/7703720389
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
* …
> Keep GitHub Actions up to date with GitHub's Dependabot

- LICENSE
- changelog/996.trivial
Fixes issue with license file format to allow security scanners such as Black Duck to correctly identify the license type of this project as MIT.
> Update LICENSE formatting

- docs/distribution.rst
- src/xdist/looponfail.py
- src/xdist/plugin.py
Fix #1021 and review formatting of the --help messages, following pytest's rules for consistency.
```
distributed and subprocess testing:
-n numprocesses, --numprocesses=numprocesses
Shortcut for '--dist=load --tx=NUM*popen'.
With 'logical', attempt to detect logical CPU count (requires psutil, falls back to 'auto').
With 'auto', attempt to detect physical CPU count. If physical CPU count cannot be determined, falls back to 1.
Forced to 0 (disabled) when used with --pdb.
--maxprocesses=maxprocesses
Limit the maximum number of workers to process the tests when using --numprocesses with 'auto' or 'logical'
--max-worker-restart=MAXWORKERRESTART
Maximum number of workers that can be restarted when crashed (set to zero to disable this feature)
--dist=distmode       Set mode for distributing …
```
> Fix '-n logical' inconsistencies and review --help formatting

- changelog/1028.bugfix
- src/xdist/looponfail.py
- testing/test_looponfail.py
The setuptools implementation of editable installs will insert a placeholder entry into sys.path as part of its magic to register its custom import mechanism.
These are not real filesystem paths and as such should not be rewritten to absolute paths.
This is a proposed fix for #1028 .
Checklist:
> - [ ] Make sure to include reasonable tests for your change if necessary
I couldn't figure out how to test this specific behavior, but happy to add one given guidance on how to modify `sys.path` in the test environment.
> - [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file
Added.
> Avoid modifying path placeholders created by editable installs

- changelog/937.bugfix
- src/xdist/plugin.py
- testing/test_plugin.py
> Fix incompatibility error with `--pdb` despite using `-n0`

- src/xdist/remote.py
- src/xdist/workermanage.py
- testing/test_remote.py
It's available since pytest 5.2, and pytest-xdist requires pytest>=6.2.
> Remove pytest InvocationParams backward compat

- changelog/1024.bugfix
- src/xdist/dsession.py
- src/xdist/remote.py
- testing/acceptance_test.py
Terminate the test loop if `shouldfail` or `shouldstop` is set in a worker's pytest `session`
Closes #1024.
> Terminate the test loop if `shouldfail` or `shouldstop` is set

- .github/workflows/test.yml
- changelog/1053.removal
- pyproject.toml
- tox.ini
> Drop support for Python 3.7

- testing/acceptance_test.py
The `testdir` fixture is soft-deprecated in favor of `pytester`.
> testing: replace `testdir` -> `pytester`

- .pre-commit-config.yaml
- changelog/1057.removal
- pyproject.toml
- src/xdist/dsession.py
- src/xdist/looponfail.py
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadscope.py
- src/xdist/scheduler/worksteal.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/test_looponfail.py
- testing/test_remote.py
- tox.ini
> Bump min pytest to 7.0.0

- .pre-commit-config.yaml
- pyproject.toml
- src/xdist/dsession.py
- src/xdist/looponfail.py
- src/xdist/remote.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/loadscope.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/conftest.py
- testing/test_dsession.py
- testing/test_looponfail.py
These are some commits I made while adding typing to the plugin (will send a PR after this one is merged).
> Pre-typing fixes/improvements

- src/xdist/dsession.py
- src/xdist/scheduler/__init__.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadscope.py
- src/xdist/scheduler/protocol.py
- Clearly delineate the required interface of schedulers
- Useful for typing
> Add a Scheduling Protocol

- .pre-commit-config.yaml
- changelog/1057.trivial
- pyproject.toml
- src/xdist/dsession.py
- src/xdist/looponfail.py
- src/xdist/newhooks.py
- src/xdist/plugin.py
- src/xdist/remote.py
- src/xdist/report.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadfile.py
- src/xdist/scheduler/loadgroup.py
- src/xdist/scheduler/loadscope.py
- src/xdist/scheduler/worksteal.py
- src/xdist/workermanage.py
- testing/acceptance_test.py
- testing/conftest.py
- testing/test_dsession.py
- testing/test_looponfail.py
- testing/test_plugin.py
- testing/test_remote.py
- testing/test_workermanage.py
- testing/util.py
This adds type annotations such that we pass `mypy --strict`. The typings are not exposed as that would need some work on the public API.
Fix #1057.
> Improve typing

- changelog/1027.improvement.rst
- changelog/620.bugfix
- src/xdist/looponfail.py
- src/xdist/workermanage.py
- testing/test_remote.py
- testing/test_workermanage.py
Use the execnet `main_thread_only `execmodel so that code which expects to run in the main thread will just work.  This execmodel has been merged to the execnet master branch via pytest-dev/execnet#243, so this patch should not be merged until there is a released version of execnet supporting the `main_thread_only` execmodel.
Also increase minimum python version to 3.8 since execnet dropped 3.7 support in pytest-dev/execnet#245.
Closes: pytest-dev/pytest-xdist#620
> Use execnet main_thread_only execmodel

- changelog/1071.bugfix
- src/xdist/workermanage.py
Cache execnet gateway info during WorkerController setup for backward
compatibility, in order to avoid a later main_thread_only deadlock
error triggered when pytest-cov calls rinfo after the main thread is
already busy. See pytest-dev/execnet#274 for corresponding test case.
Fixes: 20e3ac774e8f ("Use execnet main_thread_only execmodel (#1027)")
I was able not able to reproduce the issue using a small project with pytest-xdist and pytest-cov.
I was able to reproduce it by running tox in a checkout of setuptools, after using pip to install pytest-xdist-3.6.0 into the .tox/py virtualenv. Then I applied this PR to the virtualenv and that fixed the issue, with pytest-cov successfully producing coverage results.
> Cache execnet gateway rinfo during WorkerController setup

- .github/workflows/deploy.yml
Follow up to https://github.com/pytest-dev/pytest-xdist/pull/1123.
> Publish package with attestations

- changelog/1144.feature
- src/xdist/remote.py
- testing/test_remote.py
Either unschedule all requested tests, or none if it's not possible - if some of the requested tests have already been processed by the time the request arrives. It may happen if the worker runs tests faster than the controller receives and processes status updates. But in this case maybe it's just better to let the worker keep running.
This is a prerequisite for group/scope support in worksteal scheduler - so they won't be broken up incorrectly.
This change could break schedulers that use "steal" command. However:
1) worksteal scheduler doesn't need any adjustments.
2) I'm not aware of any external schedulers relying on this command yet.
So I think it's better to keep the protocol simple, not complicate it for imaginary compatibility with some unknown and likely non-existent schedulers.
> Make 'steal' command atomic

- .github/workflows/test.yml
- changelog/1162.removal.rst
- pyproject.toml
- src/xdist/_path.py
- src/xdist/dsession.py
- src/xdist/looponfail.py
- src/xdist/newhooks.py
- src/xdist/remote.py
- src/xdist/report.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadscope.py
- src/xdist/scheduler/protocol.py
- src/xdist/scheduler/worksteal.py
- src/xdist/workermanage.py
- testing/conftest.py
- testing/test_dsession.py
- testing/test_remote.py
- tox.ini
Also executed `pyupgrade --py39-plus` on all files.
> Drop EOL Python 3.8 support

- changelog/1170.feature
- docs/remote.rst
- src/xdist/plugin.py
- src/xdist/scheduler/each.py
- src/xdist/scheduler/load.py
- src/xdist/scheduler/loadscope.py
- src/xdist/scheduler/worksteal.py
- src/xdist/workermanage.py
- testing/test_plugin.py
- testing/test_workermanage.py
This adds the feature requested in issue #1170 .
Add the `proxy` attribute to the xspec in order to create proxy gateways.
Proxy gateways do not run tests, and aren't considered as additional workers.
Proxy gateways must be named (must have an `id` attribute), and need to be passed using the `via` keyword to additional gateways.
Example:
```
pytest -sv --dist=load --tx "socket=IP:PORT//id=my_proxy//proxy" --tx "5*popen//via=my_proxy" 
```
> Add proxy gateways

- changelog/1190.trivial.rst
- pyproject.toml
[PEP 639](https://peps.python.org/pep-0639/) added support for SPDX license identifier.
Metadata diff
```diff
...
-License: MIT License
-        
-        Copyright (c) 2010 Holger Krekel and contributors.
-        
-        Permission is hereby granted, free of charge, to any person obtaining a copy
-        of this software and associated documentation files (the "Software"), to deal
-        in the Software without restriction, including without limitation the rights
-        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-        copies of the Software, and to permit persons to whom the Software is
-        furnished to do so, subject to the following conditions:
-        
-        The above copyright notice and this permission notice shall be included in …
```
> Use SPDX license identifier

- docs/distribution.rst
I found that `-n 0` was not properly documented, just in this mention in the "how to" guide:
https://github.com/pytest-dev/pytest-xdist/blob/f83299cd646965ac0560adddcf7204adde9f486e/docs/how-to.rst?plain=1#L21-L22
Plus some error messages and docstrings like:
https://github.com/pytest-dev/pytest-xdist/blob/8074c633c8ff30e0c5656888ae71fd81888396f4/src/xdist/plugin.py#L305-L308
This PR makes it explicit. I don't think a changelog entry is required.
```
Fix issue with non-ascii contents in doctest text …
```
> Document disabling with '-n 0'

- CHANGELOG.rst
- changelog/1092.trivial
- changelog/1142.feature.rst
- changelog/1144.feature
- changelog/1162.removal.rst
- changelog/1170.feature
- changelog/1190.trivial.rst
- changelog/1200.feature
> Release 3.7.0

- src/xdist/remote.py
Will come back and fill out the description. This is a possible solve of https://github.com/pytest-dev/pytest-xdist/issues/1215 for review.
The previous code before https://github.com/pytest-dev/pytest-xdist/pull/1201 called `__str__` on all group names via the f-string coercion
> Ensure all xdist group names are strings

- .github/workflows/test.yml
- changelog/1252.feature.rst
- pyproject.toml
- tox.ini
This includes integrating the corresponding envs in tests (GHA + tox) and adding a Trove classifier.
> Declare support for Python 3.14

- .github/workflows/test.yml
This should be faster than having tox build it every time from sdist. Looks like this saves about 10 seconds per job.
> Install the wheel in tox env @ CI
