xdist/dsession.py

Apologies if I've misunderstood the original intention behind any of the original text and made an inappropriate change. Let me know and I'd be happy to make the appropriate adjustments.

Typo fixes to docstrings

---

testing/acceptance_test.py

Mark test_each_multiple as xfail

---

CHANGELOG
testing/acceptance_test.py
xdist/slavemanage.py

xdist now works if the internal tmpdir plugin is disabled

---

CHANGELOG
testing/acceptance_test.py
xdist/looponfail.py
xdist/plugin.py

Make xdist work even if looponfail or boxed are disabled

---

testing/acceptance_test.py

Will try to rebuild this a few times on Travis to ensure it is working
Fix #30

Fix test_auto_detect_cpus flakyness

---

CHANGELOG
README.rst
testing/acceptance_test.py
xdist/plugin.py

Fix flakes, add CHANGELOG and improve test a bita
Supersedes #48

Worker id fixture

---

CHANGELOG
testing/acceptance_test.py
xdist/remote.py

Fix internal error when a fixture raises an exception

---

README.rst

Also bring Travis and AppVeyor badges near each other

Add a badge for the anaconda package

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst
HOWTORELEASE.rst
changelog/154.doc
changelog/155.doc
changelog/_template.rst
dev-requirements.txt
pyproject.toml

Add towncrier and HOWTORELEASE docs

---

testing/acceptance_test.py

Make tests for loadscope deterministic

---

xdist/slavemanage.py

Fix reprcrash check in unserialize_report()

---

xdist/plugin.py

Add docstring for worker_id

---

.travis.yml

Change Travis configuration to use stages in CI

---

.travis.yml

move distributions key to the right place
install setuptools_scm for deploy

fix up travis deploy config

---

.travis.yml
appveyor.yml
testing/acceptance_test.py
tox.ini

Fix tests in pytest >= 3.3 and add it to build matrix

---

README.rst

Grammar fix

---

ISSUES.txt
README.rst
example/boxed.txt
example/loadscope/tox.ini
setup.py
tox.ini
xdist/dsession.py
xdist/looponfail.py
xdist/workermanage.py

http://blog.pytest.org/2016/whats-new-in-pytest-30/
https://twitter.com/hashtag/dropthedot
```
```

Use pytest instead of py.test per upstream recommendation, #dropthedot

---

.travis.yml
appveyor.yml
changelog/341.bugfix.rst
testing/acceptance_test.py
tox.ini
xdist/dsession.py
xdist/remote.py
xdist/workermanage.py

Fix warnings transfer between workers and master node with pytest >= 3.8

---

changelog/344.bugfix
testing/acceptance_test.py
xdist/remote.py
xdist/workermanage.py

add exception handeling for warning serialization issues

---

.travis.yml
appveyor.yml
changelog/349.bugfix.rst
testing/acceptance_test.py
tox.ini
xdist/remote.py
xdist/workermanage.py

Handle warnings with unserializable arguments

---

changelog/384.bugfix.rst
xdist/workermanage.py

Fix https://github.com/pytest-dev/pytest-xdist/issues/387.

Fix ExceptionInfo usage for pytest 4.1

---

README.rst

Add docs for sys.argv access from workers

---

setup.py
testing/acceptance_test.py
testing/test_remote.py

Also uniformize the usage of the `with` context manager.
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

Fix ResourceWarning: unclosed file in setup.py

---

changelog/442.feature.rst
src/xdist/remote.py

Related to pytest-dev/pytest#5420

Compatibility for IntEnum change in upcoming pytest 5.0

---

CHANGELOG.rst
changelog/448.feature.rst
changelog/467.bugfix.rst

prepare 1.30.0 release

---

.appveyor.yml
.travis.yml
tox.ini

pytest is using the master branch now only.

tox/ci: remove testing with pytest's features branch

---

README.rst

Fix "acessing" typo in readme

---

CHANGELOG.rst
changelog/475.removal
changelog/524.feature

Well, let's make a new release then.

Prepare version 1.32.0

---

.travis.yml
changelog/566.bugfix
testing/acceptance_test.py
tox.ini

Continuation from #566
Closes #566

Fix test_config_initialization skipif check and add py39 testing

---

src/xdist/dsession.py
src/xdist/remote.py
testing/acceptance_test.py

Follow up to https://github.com/pytest-dev/pytest-xdist/pull/541

Drop features from old pytest versions

---

.pre-commit-config.yaml
changelog/573.trivial.rst

run pyupgrade in ci

---

README.rst

Fix session-scoped fixtures example in README

---

README.rst

trivial: Fixed typo in README

---

README.rst

doc: fix invalid url(socketserver.py)

---

setup.py

Add python 3.9 to classifiers

---

CHANGELOG.rst
changelog/623.bugfix.rst

release 2.2.1

---

.github/workflows/main.yml
changelog/643.trivial.rst
tox.ini

 Use 'main' to refer to pytest default branch in tox env names.

---

README.rst

Document that -s doesn't work with pytest-xdist

---

README.rst

Document two missing arguments

---

testing/test_workermanage.py
testing/util.py

As explained in https://github.com/pytest-dev/pytest-xdist/issues/404#issuecomment-1073998712

Added a couple tests for #404

---

.github/workflows/main.yml
.pre-commit-config.yaml
setup.cfg

run pipx run pre-commit autoupdate

---

CHANGELOG.rst
changelog/884.bugfix

Unless someone else plans to land another fix in a few following days, I'd like to make a bugfix release.

Release 3.2.1

---

docs/remote.rst

Fix link to socketserver.py in the docs

---

docs/conf.py

Fixed an outdated year in the project documentation

Fix year in project documentation

---

.pre-commit-config.yaml
pyproject.toml
src/xdist/__init__.py
src/xdist/_path.py
src/xdist/dsession.py
src/xdist/looponfail.py
src/xdist/newhooks.py
src/xdist/plugin.py
src/xdist/remote.py
src/xdist/scheduler/__init__.py
src/xdist/scheduler/each.py
src/xdist/scheduler/load.py
src/xdist/scheduler/loadfile.py
src/xdist/scheduler/loadgroup.py
src/xdist/scheduler/loadscope.py
src/xdist/scheduler/worksteal.py
src/xdist/workermanage.py
testing/acceptance_test.py
testing/conftest.py
testing/test_dsession.py
testing/test_looponfail.py
testing/test_newhooks.py
testing/test_plugin.py
testing/test_remote.py
testing/test_workermanage.py
tox.ini

Use ruff instead of black, flake8, autoflake, pyupgrade

---

.github/workflows/test.yml
tox.ini

Make sure we don't break the promise.

ci: add a job for min supported pytest version

---

.pre-commit-config.yaml
changelog/1057.removal
pyproject.toml
src/xdist/workermanage.py
testing/test_workermanage.py

This version adds typing which we want to utilize.

Bump min execnet to 2.1.0

---

.github/workflows/test.yml
changelog/1142.feature.rst
pyproject.toml
tox.ini

Added support for Python 3.13

---

.pre-commit-config.yaml
changelog/1200.feature
docs/distribution.rst
src/xdist/remote.py
testing/acceptance_test.py

Join multiple xdist_group
